version: '3'

services:
  reverse-proxy:
    image: traefik # The official Traefik docker image
    command: --docker #  tells Traefik to listen to docker
    ports:
      - "8000:80"     # The HTTP port
#      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  app:
    image: nbapp #:gunicorn #:gunicorn #suvarchal/nbapp 
    labels:
      - "traefik.frontend.rule=Host:localhost"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    user: "1000:133" #133 here is docker group id from shell command id
    expose:
      - "5000" #"8000" #5000 for nbapp
    ports:
      - "5000:5000" #"8000" #5000 for nbapp
    environment:
      - JUPYTER_CONTAINER=suvarchal/drilsdown # use any valid jupyter notebook container
      - CULL_IDLE_TIMEOUT=30  # remove idle notebooks after N seconds
      - RAMADDA_BASE_URL=http://ramadda:8080/repository 
      - NOTEBOOK_HOST=localhost
    depends_on:
      - redis 
      - ramadda 

 #   networks:
 #     - traefik_default

  ramadda:
    image: suvarchal/ramadda-geoscience:update
    
    labels:
      - "traefik.backend=ramadda"
      - "traefil.backend.rule=Host:ramadda:8080;PathPrefix:/repository"
      - "traefik.frontend.rule=Host:localhost;PathPrefix:/repository"
    
    volumes:
      - /repository:/data/repository
    expose:
      - "8080"

  redis:
    image: redis
#    ports:
#      - "6379:6379"
#      - "6380:6380"
    expose:
      - "6379"
    #volumes:
    #  - "/home/suvarchal/docker/data:/data"
#    networks:
#      - traefik_default
    command: redis-server --appendonly yes
#  networks:
#    traefik_default:
